#!/bin/bash
Green="\e[92;1m"
RED="\033[1;31m"
NC='\033[0m'
OR='\033[1;93m'
grenbo="\e[92;1m"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://script.siglipanel.com/ip"
city=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
domain=$(cat /etc/xray/domain)
isp=$(cat /etc/xray/isp | cut -d ' ' -f 1-2)

RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
#MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
#LOADCPU=$(printf '%-3s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g' | cut -d '.' -f 1-3 )
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
versi=$(wget -qO- https://script.siglipanel.com/version)
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
if [ ! -e /etc/vmess ]; then
    mkdir -p /etc/vmess
    touch /etc/vmess/.vmess.db
fi
vms=$(cat /etc/vmess/.vmess.db)
if [[ $vms = "" ]]; then
    vm="0"
else
    vm=$(cat /etc/vmess/.vmess.db | grep "###" | wc -l)
fi

if [ ! -e /etc/vless ]; then
    mkdir -p /etc/vless
    touch /etc/vless/.vless.db
fi
vms=$(cat /etc/vless/.vless.db)
if [[ $vms = "" ]]; then
    vl="0"
else
    vl=$(cat /etc/vless/.vless.db | grep "###" | wc -l)
fi

if [ ! -e /etc/trojan ]; then
    mkdir -p /etc/trojan
    touch /etc/trojan/.trojan.db
fi
vms=$(cat /etc/trojan/.trojan.db)
if [[ $vms = "" ]]; then
    tr="0"
else
    tr=$(cat /etc/trojan/.trojan.db | grep "###" | wc -l)
fi
if [ ! -e /etc/shadowsocks ]; then
    mkdir -p /etc/shadowsocks
    touch /etc/shadowsocks/.shadowsocks.db
fi
vms=$(cat /etc/shadowsocks/.shadowsocks.db)
if [[ $vms = "" ]]; then
    ss="0"
else
    ss=$(cat /etc/shadowsocks/.shadowsocks.db | grep "###" | wc -l)
fi
if [ ! -e /etc/ssh ]; then
    mkdir -p /etc/ssh
    touch /etc/ssh/.ssh.db
fi
vms=$(cat /etc/ssh/.ssh.db)
if [[ $vms = "" ]]; then
    ssh="0"
else
    ssh=$(cat /etc/ssh/.ssh.db | grep "###" | wc -l)
fi
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$((($d1 - $d2) / 86400))
magenta="\033[1;35m"
green="\033[1;32m"
white="\033[1;37m"
blue="\033[1;34m"
red="\033[1;31m"
black="\033[1;40;30m"
yellow="\033[1;33m"
cyan="\033[1;36m"
reset="\033[0m"
bgyellow="\033[1;43;33m"
bgwhite="\033[1;47;37m"
bru="\033[0;36m"
c0=${reset}
c1=${magenta}
c2=${green}
c3=${white}
c4=${blue}
c5=${red}
c6=${yellow}
c7=${cyan}
c8=${black}
c9=${bgyellow}
c10=${bgwhite}
c11=${bru}
clear
echo -e "  ${OR}──────────────────────────────────────${NC}"
printf "\e[1;92m           .::::. \e[0m\e[1;77m MLAK  \e[1;92m.::::.\e[0m\n"
echo -e "  ${OR}──────────────────────────────────────${NC}"
echo -e "      ${OR}┌───────────────────────────┐${NC}"
echo -e "      ${OR}│ ${NC}${RED}SYS OS :${NC} $MODEL"
echo -e "      ${OR}│ ${NC}${RED}RAM :${NC} $RAM MB/$USAGERAM MB "
echo -e "      ${OR}│ ${NC}${RED}UP :${NC} $SERONLINE"
echo -e "      ${OR}│ ${NC}${RED}CORE :${NC} $CORE"
echo -e "      ${OR}│ ${NC}${RED}ISP :${NC} $isp"
echo -e "      ${OR}│ ${NC}${RED}CITY :${NC} $city"
echo -e "      ${OR}│ ${NC}${RED}IP :${NC} $ipsaya"
echo -e "      ${OR}│ ${NC}${RED}DOMAIN :${NC} $domain"
echo -e "      ${OR}│ ${NC}${RED}NS :${NC} $NS"
echo -e "      ${OR}└────────────────────────────┘${NC}"
echo -e "           SSH OVPN: $ssh VMESS: $vm"
echo -e "       VLESS: $vl TROJAN: $tr SHADWSK: $ss"
echo -e "  ${OR}┌──────────────────────────────────────┐${NC}"
echo -e "  ${OR}│${NC}  ${grenbo}1.${NC}${c11}SSH OVPN MANAGER${NC} ${grenbo}4.${NC}${c11}TROJAN MANAGER${NC}"
echo -e "  ${OR}│${NC}  ${grenbo}2.${NC}${c11}VMESS MANAGER${NC}    ${grenbo}5.${NC}${c11}SHDWSK MANAGER${NC}"
echo -e "  ${OR}│${NC}  ${grenbo}3.${NC}${c11}VLESS MANAGER${NC}    ${grenbo}6.${NC}${c11}OTHER SETTINGS${NC}"
echo -e "  ${OR}└──────────────────────────────────────┘"
echo -e "  ${grenbo}         Version script $versi${NC} "
echo -e "           ${c1}━━━${c2}━━━${c3}━━━${c4}━━━${c5}━━━${c6}━━━${c7}━━${NC}"
echo -e ""
read -p "     Select From Options [ 1 - 6 ] : " menu
case $menu in
    1) mssh ;;
    2) mvmess ;;
    3) mvless ;;
    4) mtrojan ;;
    5) mshadowsocks ;;
    6) msettings ;;
    
    *)
        echo ""
        exit 0
    ;;
esac